version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web_app:
    build: .
    command: sh -c 'python manage.py migrate && python manage.py makemigrations && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - /app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SUPERUSER_USERNAME=admin4
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      - postgres
